# -*- coding: utf-8 -*-
"""'simple_code.py'

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1INK3NTdTWeEXCA0lrYe__KHFI-WI4nX7
"""

# List of team members and their details
team = [
    {
        "name": "Zakia Salod",
        "slack_username": "Zakia Salod",
        "country": "South Africa",
        "hobby": "Art",
        "affiliation": "University of KwaZulu-Natal",
        "favorite_gene_dna": "ATGCGTACGTTAGCCTGA"
    },
    {
        "name": "Poornavaishnavi Chekuri",
        "slack_username": "Vaishnavi",
        "country": "USA",
        "hobby": "Knowledge Hunter",
        "affiliation": "University of Houston-Clear Lake",
        "favorite_gene_dna": "CGTATCGATCGATGCTAG"
    },
    {
        "name": "Clemence Usanase",
        "slack_username": "Clemence",
        "country": "Rwanda",
        "hobby": "TV shows",
        "affiliation": "Not Available",
        "favorite_gene_dna": "TTGCGATAGCTAGCGTAA"
    },
    {
        "name": "Aaronie Jersha Jenyfred",
        "slack_username": "Jersha Fernando",
        "country": "USA",
        "hobby": "Bookreading",
        "affiliation": "Northeastern University",
        "favorite_gene_dna": "ATCGGATACCGTTAAGGA"
    },
    {
        "name": "Abane Louis Ashu",
        "slack_username": "Louis",
        "country": "Cameroon",
        "hobby": "Investing and Trading",
        "affiliation": "Universite Libre de Brussels (ULB), Belgium",
        "favorite_gene_dna": "CGTAGGCTAACGTTCGTA"
    },
    {
        "name": "Hasiba Asma",
        "slack_username": "Hasiba asma",
        "country": "Pakistan",
        "hobby": "Exploring AI with bioinformatics",
        "affiliation": "Sepal AI",
        "favorite_gene_dna": "AATGCCGTAGGCTTACGA"
    }
]

# Print each team member's details
for person in team:
    print(f"Name: {person['name']}")
    print(f"Slack Username: {person['slack_username']}")
    print(f"Country: {person['country']}")
    print(f"Hobby: {person['hobby']}")
    print(f"Affiliation: {person['affiliation']}")
    print(f"Favorite Gene DNA Sequence: {person['favorite_gene_dna']}")
    print("-" * 50)